# Generated by Django 5.0.6 on 2024-06-10 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_alter_keymodel_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="keymodel",
            old_name="key",
            new_name="api_key",
        ),
    ]
