# Generated by Django 5.0.6 on 2024-06-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("external_id", models.IntegerField(default=0)),
                ("author", models.CharField(max_length=255)),
                ("views_count", models.IntegerField(default=0)),
                ("position", models.IntegerField()),
            ],
        ),
    ]
